### ISSUE TITLE
Where is readme.md?

### ISSUE THREAD

**Issue by Junyan721113** [iMikeLiu/JieQianXiongXin#1]
能不能加一个readme之类的。。。

**Comment by iMikeLiu** [comment]
您好，llh721113：
        我正在计划编写一个Readme.md，为了新用户。没有Readme.md因为我有不多的时间。

**Comment by iMikeLiu** [comment]
我已经增加了自述文件，这个发出将会被关闭。感谢反馈噪音，请等一下我们的投影。
