### ISSUE TITLE
Stup*d Mechanical Translation

### ISSUE THREAD

**Issue by Junyan721113** [iMikeLiu/JieQianXiongXin#4]
Just close it，please.

**Comment by iMikeLiu** [comment]
您好，llh721113：
机械的翻译不是我们需求，为了我们更好的服务。说英语的人将会翻译到英语简单地没有错误。所以我们将会继续使用机械的翻译风格。

Hello,llh721113:
Mechanical translation is not what we need, for our better service. English speakers will translate into English simply without mistakes. So we will continue to use mechanical translation style.
